name: ci
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
