name: deploy
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rsync-and-restart:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY:  ${{ secrets.SSH_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Verify required secrets
        run: |
          [ -n "$SSH_HOST" ] && [ -n "$SSH_USER" ] && [ -n "$SSH_KEY" ] || { echo "Missing secrets SSH_HOST/SSH_USER/SSH_KEY"; exit 1; }

      - name: Ensure remote path exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            set -euo pipefail
            mkdir -p /opt/hardlock

      - name: Rsync repo (exclude sensitive/CI files)
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete --exclude '.git/' --exclude '.github/' --exclude '.env' --exclude 'DEPLOY_TRIGGER'
          path: ./
          remote_path: /opt/hardlock/
          remote_host: ${{ env.SSH_HOST }}
          remote_user: ${{ env.SSH_USER }}
          remote_key: ${{ env.SSH_KEY }}

      - name: Restart stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            set -euo pipefail
            cd /opt/hardlock
            docker compose build
            docker compose up -d --remove-orphans
            /usr/local/bin/hardlock-status
