name: deploy
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rsync-and-restart:
    runs-on: ubuntu-latest
    if: ${{ secrets.SSH_HOST && secrets.SSH_USER && secrets.SSH_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Rsync sources to VM
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete
          path: |
            api/
            kms-rs/
            docker-compose.yml
            Caddyfile
          remote_path: /opt/hardlock/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Restart stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            cd /opt/hardlock
            docker compose build
            docker compose up -d --remove-orphans
            /usr/local/bin/hardlock-status
