name: smoke-cron
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      TARGET_IP: 51.15.200.66
      HOSTS: "tufkey.com api.tufkey.com kms.tufkey.com"
    steps:
      - name: Check public HTTPS endpoints (DNS bypass, IPv4, retries)
        run: |
          set -e
          for h in $HOSTS; do
            url="https://$h/health"
            code=$(curl -4 -sk --connect-timeout 5 --max-time 12 --retry 3 --retry-delay 2 --resolve "$h:443:$TARGET_IP" -o /dev/null -w "%{http_code}" "$url" || true)
            echo "$h => $code"
            [ "$code" = "200" ] || exit 1
          done
