name: smoke-cron
on:
  schedule:
    - cron: '7,22,37,52 * * * *'
  workflow_dispatch:
concurrency:
  group: smoke-cron
  cancel-in-progress: true
jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      TARGET_IP: 51.15.200.66
      HOSTS: "tufkey.com api.tufkey.com kms.tufkey.com"
    steps:
      - name: Warm-up
        run: sleep 10
      - name: External DNS-bypass (2/3 consensus, 3 rounds, IPv4)
        run: |
          set -e
          ok=0
          for h in $HOSTS; do
            pass=0
            for r in 1 2 3; do
              c=$(curl -4 -sk --connect-timeout 8 --max-time 20 --retry 3 --retry-delay 2 --retry-all-errors \
                   --resolve "$h:443:$TARGET_IP" -o /dev/null -w "%{http_code}" "https://$h/health" || echo 000)
              echo "bypass $h r=$r => $c"
              [ "$c" = "200" ] && pass=1 && break
              sleep 3
            done
            [ $pass -eq 1 ] && ok=$((ok+1))
          done
          echo "bypass_ok=$ok"
          [ "$ok" -ge 2 ]
